# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# set work directory
WORKDIR /app

# Install build dependencies, git (needed for AlphaGenome), and curl (for health checks)
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential git curl && rm -rf /var/lib/apt/lists/*

# Copy requirements (pyproject.toml, etc.)
COPY pyproject.toml .
COPY README.md .
COPY LICENSE .

# Copy source code
COPY src ./src
COPY tests ./tests
COPY Makefile .
COPY tox.ini .

# Install the package with worker dependencies
RUN pip install --upgrade pip && pip install .[worker]

# Clone and install AlphaGenome
RUN git clone https://github.com/google-deepmind/alphagenome.git /tmp/alphagenome && \
    pip install /tmp/alphagenome && \
    rm -rf /tmp/alphagenome

# Expose port for remote MCP connections
EXPOSE 8000

# Set default mode to streamable_http for Docker deployments
ENV MCP_MODE=streamable_http

# Health check for the MCP server
# Use -L to follow redirects from /mcp to /mcp/
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -sfL -X POST http://localhost:8000/mcp \
        -H "Content-Type: application/json" \
        -H "Accept: application/json, text/event-stream" \
        -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"healthcheck","version":"1.0"}}}' \
        | grep -q "protocolVersion" || exit 1

# Run the MCP server with configurable mode
CMD ["sh", "-c", "biomcp run --mode ${MCP_MODE}"]
